CREATE TABLE classes (
  class_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
  class_name TEXT NOT NULL,
  days TEXT,
  times TEXT,
  location TEXT,
  room TEXT
);